apiVersion: v1
kind: Secret
metadata:
  name: { { include "pgstudio.fullname" . } }-secret
  labels:
    {{- include "pgstudio.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: { { include "pgstudio.databaseUrl" . | quote } }
  JWT_SECRET: { { required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote } }
  JWT_REFRESH_SECRET: { { required "secrets.jwtRefreshSecret is required" .Values.secrets.jwtRefreshSecret | quote } }
  CREDENTIALS_ENCRYPTION_KEY: { { required "secrets.credentialsEncryptionKey is required" .Values.secrets.credentialsEncryptionKey | quote } }
  { { - if .Values.postgres.enabled } }
  POSTGRES_PASSWORD: { { required "postgres.auth.password is required" .Values.postgres.auth.password | quote } }
  { { - end } }
