apiVersion: v1
kind: Service
metadata:
  name: { { include "pgstudio.fullname" . } }-web
  labels:
    {{- include "pgstudio.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: { { .Values.service.web.type } }
  ports:
    - name: http
      port: { { .Values.service.web.port } }
      targetPort: http
  selector:
    app.kubernetes.io/instance: { { .Release.Name } }
    app.kubernetes.io/component: web
